### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by dotxlem** [akkoro/assemblylift#4]
"Command Line Interface" is pretty broad, but I don't want to design too much of it up-front before some other things take shape.

So, I'm thinking to keep the scope small for now, the focus should be getting something together that one could minimally install (via Cargo or w/e) and run to scaffold a new AssemblyLift project.

This of course requires a project structure to be worked out as well, which hasn't been started yet -- very much open to input here!

**Comment by OAyomide** [comment]
For starters I think good ol "create new app" type of command line interface would work (using clap.rs as expected). then things like basic configuration can be supported (for example, if there is a specific default config and if users are allowed to specify their own config).

this way, i believe incremental development can be achieved. in the future, more things can simply be supported.

**Comment by dotxlem** [comment]
Yeah I think that makes sense. `clap` looks good -- I wasn't sure what the "standard" arg parser was for rust ^^.

I was thinking of calling the binary `asml` since it's short, and I've been using that as an abbreviation in some of the code anyway.

**Comment by OAyomide** [comment]
Yeah clap-rs is like the expressjs of command-line apps in rust :upside_down_face: 

also, asml sounds soo good :smile:

**Comment by dotxlem** [comment]
> also, asml sounds soo good 😄

Thanks! That's great -- naming things is hard, so that should save some time lol

**Comment by dotxlem** [comment]
@OAyomide merged in the first piece of this, if you're interested :) (see #7)

**Comment by OAyomide** [comment]
Nice!

I have been really busy and will be for the next week or 2. Going to do something when i am free!

**Comment by dotxlem** [comment]
No pressure! I'm just happy to have someone around to bounce things off of. Helps keep me from going crazy(er) ^^

**Comment by dotxlem** [comment]
See #14
