### ISSUE TITLE
Default to "help" when no option flag isnt passed to the cli command

### ISSUE THREAD

**Issue by OAyomide** [akkoro/assemblylift#43]
I just installed `asml` and by convention, i just typed ```asml``` but i got a "not nice" error msg. Perhaps making it default to the usual help screen when that happens. See screenshots below

![Screenshot 2021-04-11 at 15 08 01](https://user-images.githubusercontent.com/26779597/114307484-b88fa580-9ad7-11eb-9b1a-61fa65db9a6f.png)

see cargo's (just to make my point more obvious).
![Screenshot 2021-04-11 at 15 08 34](https://user-images.githubusercontent.com/26779597/114307496-cba27580-9ad7-11eb-8670-afd4a5a9d29d.png)

is this in the pipeline or do i go ahead and do this, you know, just to step into the waters of assemblylift (so to speak)

**Comment by dotxlem** [comment]
Hey @OAyomide sorry for taking so long here, and thank you for reporting this! I have this partially fixed on the `v0.3` branch, but I don't think it will default to help (I think I just made the error message nicer)

If you want to take a look at improving this, you'll want to branch from [v0.3](https://github.com/akkoro/assemblylift/tree/v0.3) as this has the latest changes currently.

**Comment by dotxlem** [comment]
@OAyomide actually I do not have it fixed yet at all...that must have been something else 😂. Go ahead if you want to start there! :)

**Comment by OAyomide** [comment]
Oops! didnt mean to close.

alright! working on the PR then! @dotxlem

**Comment by OAyomide** [comment]
Addressed via #44 but not sure which branch to make the PR against so i made it against mainline.

**Comment by dotxlem** [comment]
Closed by #44
